### ISSUE TITLE
2016 premiership games don't play

### ISSUE THREAD

**Issue by shavanni** [glennguy/plugin.video.nrl-live#1]
I cannot access 2016 premiership games.

2015 and prior and fine as is 2016 State of Origin.

**Comment by glennguy** [comment]
Hi @shavanni , this is fixed in 1158a7c 

I'll see if I can get everything ready for the new season in the next week. Let me know if there are any further issues or requests.

**Comment by shavanni** [comment]
Thank you so much

Closing this issue
